name: Build & deploy backend

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

env:
  PROJECT_ID: petchat-85f05
  SERVICE_NAME: petchat
  PET_ID: XctAymVwTqu8onOP34ll

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Package
        run: cd server && npm ci && npm run build
      - name: Google Auth
        uses: google-github-actions/auth@v1
        id: auth
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PETCHAT_85F05 }}
          token_format: access_token
      - name: Docker Auth
        uses: docker/login-action@v1
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build & Push Container
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/server:${{ github.sha }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        uses: google-github-actions/auth@v1
        id: auth
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PETCHAT_85F05 }}
          token_format: access_token
      - name: Deploy to CloudRun
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service: ${{ format('{0}{1}', env.SERVICE_NAME, (github.event.pull_request.head.repo.full_name == github.repository && '-preview') || '') }}
          image: us-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/server:${{ github.sha }}
          env_vars: |
            NODE_ENV=production
            FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_PETCHAT_85F05 }}
            FIREBASE_AUTH_DOMAIN=${{ env.PROJECT_ID }}.firebaseapp.com
            FIREBASE_PROJECT_ID=${{ env.PROJECT_ID }}
            FIREBASE_STORAGE_BUCKET=${{ env.PROJECT_ID }}.appspot.com
            FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PETCHAT_85F05 }}
            FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID_PETCHAT_85F05 }}
            FIREBASE_ADMIN_SDK_CLIENT_EMAIL=${{ secrets.FIREBASE_ADMIN_SDK_CLIENT_EMAIL_PETCHAT_85F05 }}
            FIREBASE_ADMIN_SDK_PRIVATE_KEY=${{ secrets.FIREBASE_ADMIN_SDK_PRIVATE_KEY_PETCHAT_85F05 }}
