name: Dependabot PR Check

on:
  pull_request

jobs:
  # Job to check for dependabot
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo 'PR created by Dependabot'
